import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import uniform
from scipy.stats import binom
from scipy.stats import poisson
from scipy.stats import norm
from scipy.stats import expon

# чтобы построился следующий график необходимо закрыть предыдущий

x = np.linspace(-3, 8, 100)
y = uniform.cdf(x, 0, 4)
plt.plot(x, y, color='green', label=f'U(a={0}, b={4})')
plt.xlabel('x')
plt.ylabel('y')
plt.title('Равномерное распределение')
plt.legend()
plt.grid()
plt.show()
y = uniform.pdf(x, 0, 4)
plt.plot(x, y, color='green', label=f'U(a={0}, b={4})')
plt.xlabel('x')
plt.ylabel('y')
plt.title('Плотность равномерного распределения')
plt.legend()
plt.grid()
plt.show()

x = np.linspace(0, 29, 30)
y = binom.cdf(x, 20, 0.5)
plt.scatter(x, y, color='blue', label=f'Bin(n={20}, p={1/2})')
plt.xlabel('x')
plt.ylabel('y')
plt.title('Функция биномиального распределения')
plt.legend()
plt.grid()
plt.show()
y = binom.pmf(x, 20, 0.5)
plt.scatter(x, y, color='blue', label=f'Bin(n={20}, p={1/2})')
plt.xlabel('x')
plt.ylabel('y')
plt.title('Функция вероятности биноминального распределение')
plt.legend()
plt.grid()
plt.show()

x = np.linspace(-1, 7, 9)
y = poisson.cdf(x, 1.5)
plt.scatter(x, y, color='orange', label=f'P(m={1.5})')
plt.xlabel('x')
plt.ylabel('y')
plt.title('Распределение Пуассона')
plt.legend()
plt.grid()
plt.show()
y = poisson.pmf(x, 1.5)
plt.scatter(x, y, color='orange', label=f'P(m={1.5})')
plt.xlabel('x')
plt.ylabel('y')
plt.title('Плотность распределения Пуассона')
plt.legend()
plt.grid()
plt.show()

x = np.linspace(-5, 7, 100)
y = norm.cdf(x, 1, 2)
plt.plot(x, y, color='red', label=f'N(m={1}, s={2})')
plt.xlabel('x')
plt.ylabel('y')
plt.title('Нормальное распределение')
plt.legend()
plt.grid()
plt.show()
y = norm.pdf(x, 1, 2)
plt.plot(x, y, color='red', label=f'N(m={1}, s={2})')
plt.xlabel('x')
plt.ylabel('y')
plt.title('Плотность нормального распределения')
plt.legend()
plt.grid()
plt.show()

x = np.linspace(-2, 10, 100)
y = expon.cdf(x, 1)
plt.plot(x, y, color='purple', label=f'Exp(m={1})')
plt.xlabel('x')
plt.ylabel('y')
plt.title('Экспоненциальное распределение')
plt.legend()
plt.grid()
plt.show()
y = expon.pdf(x, 1)
plt.plot(x, y, color='purple', label=f'Exp(m={1})')
plt.xlabel('x')
plt.ylabel('y')
plt.title('Плотность экспоненциального распределения')
plt.legend()
plt.grid()
plt.show()

